# Site settings
title: 一视同仁
SEOTitle: 一视同仁的博客
header-img: img/bg.jpg
email: chen1060253623@foxmail.com
description: And we could run away. Before the light of day.
keyword: "一视同仁, C++, 中山大学, steam, 本科老咸鱼一条"
url: "https://ttony0.github.io/"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/ttony0/ttony0.github.io" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "天道酬勤."
sidebar-avatar: /img/profile.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
zhihu_username:     yi-shi-tong-ren-43
github_username:    ttony0
#facebook_username:  baiying.qiu.7
#jianshu_username:   e71990ada2fd
#twitter_username:   qiubaiying
email_username:  chen1060253623@foxmail.com




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: V0n

# Gitalk
#gitalk:
#  enable: true    #是否开启Gitalk评论
#  clientID:          6c1a55525b29dba3d057 #生成的clientID
#  clientSecret:  ca45f222ae4c592a1ca7761013f8aff3218c92a4   #生成的clientSecret
#  repo: VonLYC.github.io    #仓库名称
#  owner: VonLYC    #github用户名
#  admin: VonLYC
#  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
# ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
# ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
     {
        title: "Ender's Blog",
        href: "https://ender-coder.github.io/"
     },
     {
        title: "biubiu's Blog",
        href: "https://biubiu0719.github.io//"
     },
     {
        title: "Max.C's Blog",
        href: "http://437436999.github.io//"
     }
]
